### ISSUE TITLE
Prevent onClick

### ISSUE THREAD

**Issue by sm2017** [minwork/use-long-press#1]
@minwork I have both `use-long-press`'s`bind` and `onClick` callback
In mobile devices , I have no problem, but in desktop, When I long press , both onLongPress and `onClick` callback fired , How can I prevent  `onClick` ?

**Comment by minwork** [comment]
Hello,

could you supply some code for that specific case?

From my perspective there are three options depending on your case:

- Detect desktop device and conditionally disable onClick handler
- Use flag for conditionally disabling `onClick` callback after `onStart` is triggered
- Try `preventDefault` on event in `onStart` callback (although I am not sure that will work)

**Comment by sm2017** [comment]
```
import React from 'react';
import { useLongPress } from 'use-long-press';

const Example = () => {
    const bind = useLongPress(() => {
        //Show bottom sheet
    });
    const onClick=() => {
        //Navigate to the page
    };

    return <button {...bind} onClick={onClick}>Press me</button>;
};
```

**Comment by minwork** [comment]
Okay, so in that case you can just call `onClick` on `onCancel` callback, so when user just press and release it will trigger `onClick` and but when there is a long press it won't be triggered.

```typescript
import React from 'react';
import { useLongPress } from 'use-long-press';

const Example = () => {
  const onClick = () => {
    //Navigate to the page
  };
  const bind = useLongPress(() => {
    //Show bottom sheet
  }, {
    onCancel: onClick,
  });

  return <button {...bind}>Press me</button>;
};

```

Let me know if that works for you.

**Comment by miguelcaravantes** [comment]
it doesn't work as expect if you use cancel, the onClick be will triggered even on touch scroll. in normal on click if you click down and release outside the the component, it doesn't trigger the event, but onCancel does

**Comment by minwork** [comment]
I am not sure I understand, Could you provide some example of that situation and possibly open new issue if you think this is a bug?
