### ISSUE TITLE
Mobile on Long press, prevent default not working

### ISSUE THREAD

**Issue by sergeymild** [minwork/use-long-press#2]
Hello, i would like make long press on mobile devices and prevent default (it will highlight text and show context menu like copy text of something)
and when i'm doing something like this
```js
const longPress = useLongPress((e) => {
    e?.preventDefault()
    e?.stopPropagation()
    e!.cancelable = true
    e!.bubbles = false
    onDelete()
  }, {captureEvent: true});
```
prevent default doesn't work. it still highlight text and show default context menu

**Comment by minwork** [comment]
Hello,

have you tried disabling it by css?

```css
  -webkit-user-select: none; /* disable selection/Copy of UIWebView */
  -webkit-touch-callout: none; /* disable the IOS popup when long-press on a link */
```

**Comment by minwork** [comment]
I assume that solved your problem and will close that issue for now. Feel free to reopen it if you have any further questions.

**Comment by rushcodes** [comment]
This problem exists in Firefox Mobile on images - the context menu shows up regardless of whether preventDefault() and all that were called or not.
