### ISSUE TITLE
onCancel from touchmove with cancelOnMovement set to true

### ISSUE THREAD

**Issue by hburrows** [minwork/use-long-press#20]
Thank you for the nice module.  Good work.

Is there a good or recommended way to determine if `onCancel` is getting called due to movement when `cancelOnMovement: true` ?  I need different behavior depending on whether the user is clicking or scrolling and I can't find a good (easy) solution.  I'm thinking maybe I can check `event.type === 'touchmove'` but I'm hoping maybe state  is maintained that will indicate "reason" for onCancel getting called.  Thanks!!

**Comment by minwork** [comment]
Hey, I will address it along with #17 so there will be a additional info object passed to callbacks which will have an information of cancellation context

**Comment by minwork** [comment]
@hburrows This case will be addressed in v2 https://github.com/minwork/use-long-press/pull/23
