### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by TeoTN** [minwork/use-long-press#21]
Hey ! It's a great library, I really enjoy its simplicity and that it gets the thing done!

One minor issue I noticed when installing deps is that the react version is defined as `^16.8`, but now we have React v17 available, so this results in a warning:
```
warning " > use-long-press@1.1.1" has incorrect peer dependency "react@^16.8.0".
```

Could you please bump the version in package.json?

**Comment by minwork** [comment]
Sure

**Comment by fred-boink** [comment]
I still get the following when trying to install it on react 17.02

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: boink@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from use-long-press@1.1.1
npm ERR! node_modules/use-long-press
npm ERR!   use-long-press@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/cookies/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cookies/.npm/_logs/2021-11-26T21_26_53_158Z-debug.log

**Comment by minwork** [comment]
@fred-boink Should be fixed in new release https://github.com/minwork/use-long-press/releases/tag/v1.1.2
