### ISSUE TITLE
Not working on iOS Safari 

### ISSUE THREAD

**Issue by mjoellnier** [minwork/use-long-press#24]
Thanks for your work on this library - its awesome and works like a charme, except on iOS :/ I already tested the possible solutions on #7 and #2 but sadly with no success. 

#2 solved the problem of the text selection but now on long press there appears a display zoom instead of triggering the longpress. My simplified code looks like this: 

```typescript
  const handleStartCaptureClick = useCallback((e: LongPressEvent<Element>) => {
      e?.preventDefault();
      e?.stopPropagation();
      e!.cancelable = true;
      e!.bubbles = false;
     // business code stuff 
    },
    [dependencies]
  );

const bind = useLongPress((e) => handleStartCaptureClick(e), {
    threshold: 200,
    onFinish: handleStopCaptureClick,
    detect: LongPressDetectEvents.BOTH,
    captureEvent: true,
  });
```

on the CSS side I added as suggested 

```css
    user-select: none; /* disable selection/Copy of UIWebView */
    -webkit-user-select: none; /* disable selection/Copy of UIWebView */
    -webkit-touch-callout: none; /* disable the IOS popup when long-press on a link */
```

**Comment by minwork** [comment]
Zoom may be triggered by double tap caused by #5 so try to add `detect: 'touch'` and see if it helps
