### ISSUE TITLE
Event is missing currentTarget

### ISSUE THREAD

**Issue by paulincai** [minwork/use-long-press#26]
Scenario:
I want to long press on a React functional component with children. E.g in a list I have a contact with photo, name, status. I want to long press on the upper component that wraps the entire contact.

Presently the Event is bound to the clicked/touched selector (either photo, or name, or status). Technically this should be bound to the selector that the {...bind} is attached to. 

e.target.id on long press on the next component should be 'x'
e.currentTarget does not exist

```
<div id='x' {...bind}>
    <...photo  />
    <...name  />
    <s...status />
</div>

```

**Comment by paulincai** [comment]
ok, apparently I can get the currentTarget from onStart event.

**Comment by minwork** [comment]
Hey @paulincai, the behavior you are describing are actually fully handled by React. `bind` contains only handlers for standard react events like `onMouseDown` and it passes received event untouched (with an exception of persisting it). See https://github.com/minwork/use-long-press/blob/7bda6f76d6cd842e8f82c4c67adfd1a3aea09798/src/index.ts#L171
