### ISSUE TITLE
Right-click behaves like long-press

### ISSUE THREAD

**Issue by etabackman** [minwork/use-long-press#27]
When right-clicking momentarily (not long click), the `useLongPress` `callback` function is triggered.

How can I prevent this?

**Comment by elderapo** [comment]
This is still the case so plz don't close it :)

**Comment by minwork** [comment]
Hey, I will look into it. Looks like it needs to be handled internally within the library.

**Comment by minwork** [comment]
You can now overcome this issue by setting proper events filtering using new option `filterEvents` like this:
```
// ...
// If mouse event, pass only "main mouse button" clicks
filterEvents: (event) => 'button' in event ? event.button === 0 : true
// ...
```
See https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
