### ISSUE TITLE
Error during installation with React 18

### ISSUE THREAD

**Issue by gabrielenosso** [minwork/use-long-press#31]
npm ERR! While resolving: devices-xos-store@0.0.1
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from use-long-press@2.0.0

I suppose it needs react 18 in the peer dependencies.

**Comment by minwork** [comment]
Due to potential breaking changes, supporting React 18 will require additional testing, before adding it as peer dependency.

**Comment by minwork** [comment]
This will be addressed in the next release

**Comment by minwork** [comment]
Added experimental support for React 18 in v2.0.2

If you encounter any problems please report them as new issues.
