### ISSUE TITLE
types are not exported

### ISSUE THREAD

**Issue by dimitropoulos** [minwork/use-long-press#32]
In 1.2.0 some types (e.g. `LongPressCallback` and the enum `LongPressDetectEvents`) were exported, but in 2.0.0 they are not.  You may just need a line like `export * from './types'` in https://github.com/minwork/use-long-press/blob/master/src/index.ts#L15.

I tried importing those types from `use-long-press/dist/types` but that didn't work with esbuild since it's not an export in your package.json.

**Comment by minwork** [comment]
Thanks for the report, fixed in v2.0.2

**Comment by dimitropoulos** [comment]
that was fast! thanks!
