### ISSUE TITLE
`threshold` is only observed up to 85% of given value. How to get current value of timer?

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [minwork/use-long-press#33]
## `threshold` bug
Hi, I found out that passed threshold value is not being observed correctly by the hook. It triggers end at about 85% time elapsed. I set my button timer to 2000ms and it got triggered around 1710 to 1750 (it is not constant)

In my code I needed to add this hack:

```
const BUTTON_TIMER = 2000 //ms

...

{   ...
    threshold: BUTTON_TIMER / 0.85,
    ...
}

```
## How to get time left?
Besides that it would be ideal if I could get my hand on value of time left from the hook. Is it possible?
My use case is that I'm showing how much time left by progress bar around button

![image](https://user-images.githubusercontent.com/28536511/174447682-609cbead-2207-4ce4-9ea1-9ae3d004d056.png)

**Comment by minwork** [comment]
Hey, this behaviour is caused by specific of how `setTimeout` is working. If you want self correcting timer take a look at https://github.com/minwork/react-interval-hook
