### ISSUE TITLE
Use-long-press doesn't work on version 2.0.2

### ISSUE THREAD

**Issue by Kachanov-dev** [minwork/use-long-press#36]
I tried to run the project on version 2.0.2 and it didn't work. I had to downgrade to version 1.1.2 which is used in the base example.

**Comment by lancedolan** [comment]
Confirmed.

Found this issue after losing ~30 mins trying to get 2.0.2 working. Good to go on `~1.0.0`

**Comment by minwork** [comment]
Thanks for the report, please provide more information what exactly wasn’t working? Was there any error?

**Comment by Kachanov-dev** [comment]
@minwork 
I apologise, I saw in the documentation that the implementation differs from the example in the codesandbox. If you have time, please update the [codesandbox example](https://codesandbox.io/s/uselongpress-gnej6?fontsize=14&hidenavigation=1&theme=dark) , because it's а little confusing.

**Comment by minwork** [comment]
@Kachanov-dev I've added separate example for v2
