### ISSUE TITLE
Provide migration guide from v1 to v2 / v3

### ISSUE THREAD

**Issue by minwork** [minwork/use-long-press#44]

**Comment by Slapbox** [comment]
Anybody know how to upgrade to 2.x?

**Comment by Slapbox** [comment]
I studied the docs, examples, code, but upgrading from 1.x to 2.x doesn't work. No amount of holding down the button affects anything. 

1.x works great so we'll move back to that - but I'd love to upgrade just to remove it from the list of upgradable packages in npm-check-updates.

Thanks for the great project @minwork.

**Comment by minwork** [comment]
Hey @Slapbox what've changed between v1 and v2 is the result of `const bind = useLongPress(...)`. In v1 you received object that you could spread to component like `{...bind}` and in v2 you have function `{...bind()}` where you can pass context as argument in order to be able to access it on callbacks

**Comment by Slapbox** [comment]
It works like a charm! Thanks so much @minwork!

**Comment by minwork** [comment]
Migration guide will be released along with v3 but you can already access it [here](https://github.com/minwork/react/tree/develop/packages/use-long-press#migration)

**Comment by Slapbox** [comment]
@minwork thanks for the update! What was the default value for `detect` prior to v3?

**Comment by minwork** [comment]
`'both'`, but it will be replaced with `'pointer'` when I finish implementing PointerEvents.
