### ISSUE TITLE
Moving scrollbar doesn't triggers cancel

### ISSUE THREAD

**Issue by ZRafaF** [minwork/use-long-press#46]
Pressing and scrolling a scrollbar present inside the component doesn't cancel the action, even with `cancelOnMovement` set to `true`.

I'm running:
* React `18.2.0`
* Chrome `110.0.5481.77`

A possible solution would be to use `onScrollCapture` to call the `cancel`. At least thats what I used for my workaround.

**Comment by minwork** [comment]
Hey, that's a very interesting edge case, thank you for your report and suggested solution.

**Comment by minwork** [comment]
Hey, it is the same case as in #48 which will be addressed in v3. See [this comment](https://github.com/minwork/use-long-press/issues/48#issuecomment-1509736762) for more details

**Comment by minwork** [comment]
@ZRafaF Hey, I've addressed this issue in `use-long-press@3.0.0-alpha.5`, can you try it out and confirm if that resolves your problem? Migration guide to v3 can be found [here](https://github.com/minwork/react/tree/develop/packages/use-long-press#v2-to-v3)

**Comment by minwork** [comment]
Version 3 which addresses this issue is now available at `use-long-press@latest`
