### ISSUE TITLE
Scrolling with touch still triggers long-press

### ISSUE THREAD

**Issue by Alexsutton14** [minwork/use-long-press#6]
This may be intentional behaviour but if there are a lot of use-long-press elements on screen, and a user happens to start a touch on one of them to scroll the long press event still triggers even when scrolling. Should onTouchMove events cancel long-presses?

I've tried adding the handlers to [my fork](https://github.com/Alexsutton14/use-long-press/commit/bf4ec7ae12050fe79625c1f04b3d7355f794f045#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26), which seems to work although would be a breaking change for any existing uses where being able to move whilst touching is required.

**Comment by vatson** [comment]
@Alexsutton14 thanks for your workaround. It works fine for me. By the way, `react-use` has the same issue.

**Comment by minwork** [comment]
Thanks @Alexsutton14 for discovering that case. 
I have solution in mind so it will be addressed in the next minor version.

**Comment by minwork** [comment]
This issue will be solved by https://github.com/minwork/use-long-press/pull/8
